version: '3.3'
services:
  mongodb:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - "/data/mongodb/db:/data/db"
  api:
    build: ./api
    ports:
    - "80:80"
    depends_on:
    - 'mongodb'
volumes:
  mongodata:
